# Generated by Django 3.2.8 on 2021-11-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.product')),
            ],
        ),
    ]
