# Generated by Django 3.2.8 on 2021-11-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20211121_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.CharField(default='01/01/2021', max_length=30),
        ),
    ]
